<?php

/**
 * @file
 * Contains hooks implementation for the Pants module.
 */

/**
 * Implements hook_permission().
 */
function pants_permission() {
  return array(
    'access pants color' => array(
      'title' => t('Access pants color'),
    ),
    'administer pants settings' => array(
      'title' => t('Administer pants settings'),
    )
  );
}

/**
 * Implements hook_menu().
 */
function pants_menu() {
  $items['pants/color/%user'] = array(
    'title' => 'Get pants color',
    'page callback' => 'pants_color',
    'page arguments' => array(2),
    'access callback' => 'pants_color_access',
    'type' => MENU_CALLBACK,
    'file' => 'pants.pages.inc',
  );
  $items['admin/config/system/pants'] = array(
    'title' => 'Pants',
    'description' => 'Administer pants.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('pants_settings'),
    'access arguments' => array('administer pants settings'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'pants.admin.inc',
  );

  return $items;
}

/**
 * Access callback for the pants/color/%user menu entry.
 */
function pants_color_access() {
  return user_access('access pants color');
}

/**
 * Implements hook_block_info().
 */
function pants_block_info() {
  $blocks['pants_color'] = array(
    'info' => t('Current user\'s pants color'),
  );
  $blocks['pants_user_color'] = array(
    'info' => t('Specific user\'s pants color'),
  );

  return $blocks;
}

/**
 * Implements hook_block_configure().
 */
function pants_block_configure($delta) {
  $form = array();

  switch ($delta) {
    case 'pants_user_color':
      $query = db_select('users', 'u');
      $query->condition('u.uid', 0, '<>');
      $query->fields('u', array('uid', 'name'));
      $result = $query->execute();

      $options = array();
      foreach ($result as $item) {
        $options[$item->uid] = $item->name;
      }

      $form['pants_user_color_user'] = array(
        '#type' => 'select',
        '#options' => $options,
        '#default_value' => variable_get('pants_user_color_user', 1),
        '#title' => t('Select the user to display his pants color'),
      );
      break;
  }

  return $form;
}

/**
 * Implements hook_block_save().
 */
function pants_block_save($delta, $edit) {
  switch ($delta) {
    case 'pants_user_color':
      variable_set('pants_user_color_user', $edit['pants_user_color_user']);
      break;
  }
}

/**
 * Implements hook_block_view().
 */
function pants_block_view($delta) {
  $block = array();

  switch ($delta) {
    case 'pants_color':
      global $user;
      $account = user_load($user->uid);

      $pants_color = isset($account->pants_color[LANGUAGE_NONE][0]['value']) ? $account->pants_color[LANGUAGE_NONE][0]['value'] : variable_get('pants_default_color', 'blue');
      
      $block['subject'] = t('Your pants\'s color');
      $block['content'] = array(
        'color' => array(
          '#markup' => t('Your pants are') . ' ' . $pants_color,
        ),
        'link' => array(
          '#prefix' => '<br/>',
          '#markup' => l(t('See details'), 'pants/color/' . $account->uid),
        )
      );
      break;

    case 'pants_user_color':
      $account = user_load(variable_get('pants_user_color_user', 1));

      $pants_color = isset($account->pants_color[LANGUAGE_NONE][0]['value']) ? $account->pants_color[LANGUAGE_NONE][0]['value'] : variable_get('pants_default_color', 'blue');

      $block['subject'] = $account->name . ' ' . t('pants\'s color');
      $block['content'] = array(
        'color' => array(
          '#markup' => t('Your pants are') . ' ' . $pants_color,
        ),
        'link' => array(
          '#prefix' => '<br/>',
          '#markup' => l(t('See details'), 'pants/color/' . $account->uid),
        )
      );
      break;
  }

  return $block;
}